// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeKkERKpoxBBgMiLajZs7whoFii1hIxmw',
    appId: '1:998828132451:web:45d629cd506a6dbbee1056',
    messagingSenderId: '998828132451',
    projectId: 'tgvpn-6fce4',
    authDomain: 'tgvpn-6fce4.firebaseapp.com',
    storageBucket: 'tgvpn-6fce4.appspot.com',
    measurementId: 'G-FCMTLWKBXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJegsNhOMBGBvErucL9OFogbi8JuGXlZE',
    appId: '1:998828132451:android:cdb0c29b09957cefee1056',
    messagingSenderId: '998828132451',
    projectId: 'tgvpn-6fce4',
    storageBucket: 'tgvpn-6fce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeyeq07TqsrN3j5AJisBxFQrHL1TmnBaY',
    appId: '1:998828132451:ios:32d6c4edb17db935ee1056',
    messagingSenderId: '998828132451',
    projectId: 'tgvpn-6fce4',
    storageBucket: 'tgvpn-6fce4.appspot.com',
    iosBundleId: 'com.qdh.flutterVpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeyeq07TqsrN3j5AJisBxFQrHL1TmnBaY',
    appId: '1:998828132451:ios:de69515dcb83a07bee1056',
    messagingSenderId: '998828132451',
    projectId: 'tgvpn-6fce4',
    storageBucket: 'tgvpn-6fce4.appspot.com',
    iosBundleId: 'com.example.flutterVpn.RunnerTests',
  );
}
